name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to GFE STG
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.GFE_STG_SERVER_KEY }}
            HOSTNAME: ${{secrets.GFE_STG_URL}}
            USER_NAME: ${{secrets.GFE_STG_USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /var/www/html/test_prg/Test_repo &&
              git checkout main &&
              git fetch --all &&
              git pull origin main &&
              '
