name: Deploy
'on':
  push:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: >-
            ${{ ssh-ed25519
            AAAAC3NzaC1lZDI1NTE5AAAAIIsxbfm/4RXyF/jTCg3cf0xcnAqBq8P8fuEERZC5Grfk
            sziqbal62@gmail.com }}
          HOSTNAME: '${{secrets.3.129.25.5}}'
          USER_NAME: '${{secrets.ubuntu}}'
        run: >
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

          ssh -o StrictHostKeyChecking=no -i private_key
          ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /var/www/html/<github_test> &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/dev &&
              git pull origin main &&
              '
